[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cdm-util-scripts"
version = "0.11.0"
description = "Ohio University CONTENTdm utility scripts"
authors = [{name = "Nick Ver Steegh"}]
license = {text = "GPLv3"}
requires-python = ">=3.9"
dependencies = [
    "jinja2>=3",
    "requests>=2",
    "tqdm>=4",
    "zeep>=4.3",
]

[project.urls]
Repository = "https://github.com/OU-Libraries/cdm-util-scripts"

[project.scripts]
cdmutil = "cdm_util_scripts.cli:main"

[project.optional-dependencies]
dev = [
    "pytest>=6",
    "pytest-cov>=3",
    "pytest-recording>=0.12",
    "vcrpy>=4",
    "mypy>=0.9",
    "flake8>=3.9",
    "black>=21",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
cdm_util_scripts = [
    "templates/*",
    "py.typed",
]

[tool.pytest.ini_options]
addopts = "--cov=cdm_util_scripts --cov-report html:htmlcov"
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
